// ============================================================
// MOCK DATA — Replace with Supabase queries in production
// affiliateLinks now include per-platform price + inStock flag
// ============================================================

export const categories = [
  { id: 1, name: 'Electronics', slug: 'electronics', icon: '⚡', count: 142 },
  { id: 2, name: 'Fashion',     slug: 'fashion',     icon: '👗', count: 89  },
  { id: 3, name: 'Kitchen',     slug: 'kitchen',     icon: '🍳', count: 67  },
  { id: 4, name: 'Fitness',     slug: 'fitness',     icon: '💪', count: 54  },
  { id: 5, name: 'Beauty',      slug: 'beauty',      icon: '✨', count: 78  },
  { id: 6, name: 'Books',       slug: 'books',       icon: '📚', count: 203 },
  { id: 7, name: 'Gaming',      slug: 'gaming',      icon: '🎮', count: 45  },
  { id: 8, name: 'Home',        slug: 'home',        icon: '🏠', count: 92  },
];

// Helper: lowest price across all platforms
function bestPrice(links) {
  const prices = links.map(l => l.price).filter(Boolean);
  return prices.length ? Math.min(...prices) : 0;
}

const rawProducts = [
  {
    id: '1',
    slug: 'boat-rockerz-450-wireless-headphones',
    title: 'boAt Rockerz 450 Wireless Bluetooth On-Ear Headphones',
    shortTitle: 'boAt Rockerz 450 Headphones',
    originalPrice: 3990,
    discount: 67,
    rating: 4.1,
    reviews: 48203,
    category: 'electronics',
    tags: ['trending', 'best-seller', 'under-1500'],
    featured: true,
    isTrending: true,
    isNew: false,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&q=80',
    ],
    description: 'Premium wireless headphones with 15 hours of playtime, 40mm drivers, and foldable design. Perfect for music lovers on the go.',
    features: [
      '15 Hours Playback on single charge',
      '40mm Dynamic Drivers for immersive sound',
      'Physical Noise Isolation for better music experience',
      'Foldable design for easy portability',
      'Integrated controls & voice assistant support',
    ],
    affiliateLinks: [
      { platform: 'Amazon',   price: 1299, url: 'https://www.amazon.in/dp/example',       label: 'Buy on Amazon',   inStock: true  },
      { platform: 'Flipkart', price: 1349, url: 'https://www.flipkart.com/example',        label: 'Buy on Flipkart', inStock: true  },
      { platform: 'Meesho',   price: 1280, url: 'https://www.meesho.com/example',          label: 'Buy on Meesho',   inStock: false },
    ],
    clicks: 12430,
    videoUrl: null,
    inStock: true,
    delivery: 'Free delivery by tomorrow',
    warranty: '1 Year Manufacturer Warranty',
  },
  {
    id: '2',
    slug: 'portronics-toad-23-wireless-mouse',
    title: 'Portronics Toad 23 Wireless Optical Mouse 1600 DPI',
    shortTitle: 'Portronics Wireless Mouse',
    originalPrice: 999,
    discount: 65,
    rating: 3.9,
    reviews: 22891,
    category: 'electronics',
    tags: ['under-500', 'trending'],
    featured: false,
    isTrending: true,
    isNew: false,
    images: [
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80',
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&q=80',
    ],
    description: 'Ergonomic wireless mouse with 1600 DPI optical sensor. Works with Windows, macOS, and Linux.',
    features: [
      '1600 DPI Optical Sensor for precision',
      '2.4 GHz wireless connectivity',
      'Up to 12 months battery life',
      'Compatible with all major OS',
      'Plug & Play, no driver needed',
    ],
    affiliateLinks: [
      { platform: 'Amazon',   price: 349, url: 'https://www.amazon.in/dp/example',  label: 'Buy on Amazon',   inStock: true },
      { platform: 'Flipkart', price: 359, url: 'https://www.flipkart.com/example',  label: 'Buy on Flipkart', inStock: true },
    ],
    clicks: 8921,
    videoUrl: null,
    inStock: true,
    delivery: 'Free delivery in 2-3 days',
    warranty: '6 Months Warranty',
  },
  {
    id: '3',
    slug: 'prestige-iris-750w-mixer-grinder',
    title: 'Prestige Iris 750 Watt Mixer Grinder with 3 SS Jars',
    shortTitle: 'Prestige Iris Mixer Grinder',
    originalPrice: 4500,
    discount: 51,
    rating: 4.3,
    reviews: 31540,
    category: 'kitchen',
    tags: ['best-seller', 'trending'],
    featured: false,
    isTrending: false,
    isNew: false,
    images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&q=80'],
    description: 'Powerful 750W motor with stainless steel jars. Includes liquidizer, dry grinding, and chutney jars.',
    features: [
      '750W Powerful Motor',
      '3 Stainless Steel Jars included',
      'ABS food grade material',
      'Auto-cut overload protection',
      '5 Year Motor Warranty',
    ],
    affiliateLinks: [
      { platform: 'Amazon',   price: 2195, url: 'https://www.amazon.in/dp/example',  label: 'Buy on Amazon',   inStock: true },
      { platform: 'Flipkart', price: 2099, url: 'https://www.flipkart.com/example',  label: 'Buy on Flipkart', inStock: true },
    ],
    clicks: 5640,
    videoUrl: null,
    inStock: true,
    delivery: 'Free delivery in 3-5 days',
    warranty: '5 Year Motor, 2 Year Product Warranty',
  },
  {
    id: '4',
    slug: 'fastrack-ns28-smartwatch',
    title: 'Fastrack Reflex Rave NS28 Smart Watch 1.83" HD Display',
    shortTitle: 'Fastrack NS28 Smart Watch',
    originalPrice: 3995,
    discount: 63,
    rating: 4.0,
    reviews: 19302,
    category: 'electronics',
    tags: ['trending', 'under-1500'],
    featured: true,
    isTrending: true,
    isNew: true,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&q=80',
    ],
    description: 'Feature-packed smartwatch with 1.83" HD display, 100+ sports modes, heart rate monitoring, and 7-day battery life.',
    features: [
      '1.83" HD Display with 500 nits brightness',
      '100+ Sports Modes & Activity tracking',
      'Heart Rate & SpO2 monitoring',
      '7-day battery life',
      'IP68 Water Resistant',
    ],
    affiliateLinks: [
      { platform: 'Amazon',   price: 1495, url: 'https://www.amazon.in/dp/example',  label: 'Buy on Amazon',   inStock: true },
      { platform: 'Flipkart', price: 1449, url: 'https://www.flipkart.com/example',  label: 'Buy on Flipkart', inStock: true },
      { platform: 'Myntra',   price: 1499, url: 'https://www.myntra.com/example',    label: 'Buy on Myntra',   inStock: false },
    ],
    clicks: 9870,
    videoUrl: null,
    inStock: true,
    delivery: 'Free delivery tomorrow',
    warranty: '1 Year Warranty',
  },
  {
    id: '5',
    slug: 'wipro-9w-led-bulb-pack-of-6',
    title: 'Wipro Garnet 9W LED Bulb Cool Day White (Pack of 6)',
    shortTitle: 'Wipro 9W LED Bulb (6 Pack)',
    originalPrice: 599,
    discount: 50,
    rating: 4.2,
    reviews: 8934,
    category: 'home',
    tags: ['under-500', 'best-seller'],
    featured: false,
    isTrending: false,
    isNew: false,
    images: ['https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=600&q=80'],
    description: 'Energy saving 9W LED bulbs with 900 lumens output. BEE 5-Star rated for maximum efficiency.',
    features: [
      '9W = 75W incandescent equivalent',
      '900 Lumens bright white light',
      'BEE 5-Star Energy Rating',
      '25,000 hour lifespan',
      'No UV/IR radiation',
    ],
    affiliateLinks: [
      { platform: 'Amazon',   price: 299, url: 'https://www.amazon.in/dp/example',  label: 'Buy on Amazon',   inStock: true },
    ],
    clicks: 3210,
    videoUrl: null,
    inStock: true,
    delivery: 'Free delivery in 3-5 days',
    warranty: '2 Year Warranty',
  },
  {
    id: '6',
    slug: 'puma-unisex-training-shoes',
    title: 'PUMA Unisex-Adult Softride Premier Slip-On Running Shoes',
    shortTitle: 'PUMA Softride Slip-On Shoes',
    originalPrice: 5999,
    discount: 65,
    rating: 4.1,
    reviews: 6542,
    category: 'fashion',
    tags: ['trending', 'best-seller'],
    featured: false,
    isTrending: true,
    isNew: false,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&q=80',
    ],
    description: 'Lightweight slip-on running shoes with SOFTRIDE foam midsole for superior cushioning and comfort.',
    features: [
      'SOFTRIDE Foam midsole technology',
      'Slip-on design for easy wear',
      'Breathable mesh upper',
      'Rubber outsole for traction',
      'Available in multiple colors',
    ],
    affiliateLinks: [
      { platform: 'Amazon',   price: 2099, url: 'https://www.amazon.in/dp/example',  label: 'Buy on Amazon',   inStock: true },
      { platform: 'Flipkart', price: 1999, url: 'https://www.flipkart.com/example',  label: 'Buy on Flipkart', inStock: true },
      { platform: 'Myntra',   price: 2049, url: 'https://www.myntra.com/example',    label: 'Buy on Myntra',   inStock: true },
    ],
    clicks: 7823,
    videoUrl: null,
    inStock: true,
    delivery: 'Free delivery by tomorrow',
    warranty: '6 Months Warranty',
  },
  {
    id: '7',
    slug: 'amazon-echo-dot-5th-gen',
    title: 'Amazon Echo Dot 5th Gen Smart Speaker with Alexa',
    shortTitle: 'Amazon Echo Dot 5th Gen',
    originalPrice: 5999,
    discount: 25,
    rating: 4.4,
    reviews: 89023,
    category: 'electronics',
    tags: ['best-seller', 'trending'],
    featured: true,
    isTrending: true,
    isNew: false,
    images: ['https://images.unsplash.com/photo-1543512214-318c7553f230?w=600&q=80'],
    description: 'The most popular Echo Dot ever. Better sound, a new motion detection feature, and Alexa always ready to help.',
    features: [
      'Improved speaker for richer, louder sound',
      'Motion detection — turn lights on/off automatically',
      'Built-in Eero mesh wifi extender',
      'Privacy controls with mic-off button',
      'Works with smart home devices',
    ],
    affiliateLinks: [
      { platform: 'Amazon',   price: 4499, url: 'https://www.amazon.in/dp/example',  label: 'Buy on Amazon',   inStock: true },
    ],
    clicks: 15021,
    videoUrl: null,
    inStock: true,
    delivery: 'Free delivery tomorrow',
    warranty: '1 Year Warranty',
  },
  {
    id: '8',
    slug: 'skybags-brat-backpack-25l',
    title: 'Skybags Brat 25L Casual Laptop Backpack with USB Port',
    shortTitle: 'Skybags Brat Laptop Backpack',
    originalPrice: 2299,
    discount: 61,
    rating: 4.0,
    reviews: 12450,
    category: 'fashion',
    tags: ['under-1000', 'trending'],
    featured: false,
    isTrending: false,
    isNew: false,
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80'],
    description: '25L capacity backpack with dedicated laptop sleeve, USB charging port, and water-resistant material.',
    features: [
      '25L capacity with laptop sleeve (up to 15.6")',
      'External USB charging port',
      'Water-resistant polyester fabric',
      'Padded back support & shoulder straps',
      'Multiple pockets for organization',
    ],
    affiliateLinks: [
      { platform: 'Amazon',   price: 899, url: 'https://www.amazon.in/dp/example',   label: 'Buy on Amazon',   inStock: true },
      { platform: 'Flipkart', price: 849, url: 'https://www.flipkart.com/example',   label: 'Buy on Flipkart', inStock: true },
    ],
    clicks: 4309,
    videoUrl: null,
    inStock: true,
    delivery: 'Free delivery in 2-3 days',
    warranty: '1 Year Warranty',
  },
];

// Attach computed `price` (lowest across platforms) to every product
export const products = rawProducts.map(p => ({
  ...p,
  price: bestPrice(p.affiliateLinks),
}));

export const deals = [
  {
    id: 'd1',
    title: 'Flash Sale: 70% Off Electronics',
    endsAt: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    tag: '🔥 Hot',
    color: 'from-orange-500 to-red-500',
    products: products.filter(p => p.category === 'electronics').slice(0, 3),
  },
  {
    id: 'd2',
    title: 'Best Under ₹500',
    endsAt: null,
    tag: '💰 Value',
    color: 'from-green-500 to-emerald-500',
    products: products.filter(p => p.price < 500),
  },
  {
    id: 'd3',
    title: 'Weekend Fashion Sale',
    endsAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    tag: '⏰ Limited',
    color: 'from-purple-500 to-pink-500',
    products: products.filter(p => p.category === 'fashion'),
  },
];

export const analyticsData = {
  totalClicks: 87429,
  todayClicks: 1243,
  topProducts: [...products].sort((a, b) => b.clicks - a.clicks).slice(0, 5),
  clicksOverTime: [
    { date: 'Apr 16', clicks: 820 },
    { date: 'Apr 17', clicks: 932 },
    { date: 'Apr 18', clicks: 1100 },
    { date: 'Apr 19', clicks: 890 },
    { date: 'Apr 20', clicks: 1240 },
    { date: 'Apr 21', clicks: 1180 },
    { date: 'Apr 22', clicks: 1243 },
  ],
  categoryBreakdown: [
    { category: 'Electronics', clicks: 34200, percentage: 39 },
    { category: 'Fashion',     clicks: 19800, percentage: 23 },
    { category: 'Kitchen',     clicks: 12300, percentage: 14 },
    { category: 'Home',        clicks:  9800, percentage: 11 },
    { category: 'Others',      clicks: 11329, percentage: 13 },
  ],
};

export const getFeaturedProduct      = () => products.find(p => p.featured) || products[0];
export const getTrendingProducts     = () => products.filter(p => p.isTrending);
export const getBestUnder500         = () => products.filter(p => p.price <= 500);
export const getProductBySlug        = (slug) => products.find(p => p.slug === slug);
export const getProductsByCategory   = (category) => products.filter(p => p.category === category);
export const getRelatedProducts      = (product, limit = 4) =>
  products.filter(p => p.category === product.category && p.id !== product.id).slice(0, limit);
